fix carash after no search results. next crash due to dumb modseq query:
  09:19.60 > b'LIOG4 UID SEARCH MODSEQ 0'
  09:37.58 < b'* OK [HIGHESTMODSEQ 1292695]'
Traceback (most recent call last):
  File "/usr/lib64/python3.4/imaplib.py", line 956, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/usr/lib64/python3.4/imaplib.py", line 1076, in _get_tagged_response
    self._get_response()
  File "/usr/lib64/python3.4/imaplib.py", line 984, in _get_response
    resp = self._get_line()
  File "/usr/lib64/python3.4/imaplib.py", line 1086, in _get_line
    line = self.readline()
  File "gmail_sync.py", line 133, in readline
    ret = wrapped_readline()
  File "/usr/lib64/python3.4/imaplib.py", line 270, in readline
    raise self.error("got more than %d bytes" % _MAXLINE)
imaplib.error: got more than 10000 bytes