rtemplate: fix yaml unicode error
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/lib64/python3.5/site-packages/ansible/executor/task_executor.py", line 528, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/russ/src/ansible/action_plugins/rtemplate.py", line 99, in run
    ordered_dump(tfile.info, fp, yaml.SafeDumper)
  File "/home/russ/src/ansible/action_plugins/rtemplate.py", line 208, in ordered_dump
    return yaml.dump(data, stream, OrderedDumper, **kwds)
  File "/usr/lib64/python3.5/site-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/usr/lib64/python3.5/site-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)
  File "/usr/lib64/python3.5/site-packages/yaml/representer.py", line 27, in represent
    self.serialize(node)
  File "/usr/lib64/python3.5/site-packages/yaml/serializer.py", line 54, in serialize
    self.serialize_node(node, None, None)
  File "/usr/lib64/python3.5/site-packages/yaml/serializer.py", line 108, in serialize_node
    self.serialize_node(value, node, key)
  File "/usr/lib64/python3.5/site-packages/yaml/serializer.py", line 109, in serialize_node
    self.emit(MappingEndEvent())
  File "/usr/lib64/python3.5/site-packages/yaml/emitter.py", line 115, in emit
    self.state()
  File "/usr/lib64/python3.5/site-packages/yaml/emitter.py", line 393, in expect_first_block_mapping_key
    return self.expect_block_mapping_key(first=True)
  File "/usr/lib64/python3.5/site-packages/yaml/emitter.py", line 403, in expect_block_mapping_key
    self.expect_node(mapping=True, simple_key=True)
  File "/usr/lib64/python3.5/site-packages/yaml/emitter.py", line 244, in expect_node
    self.expect_scalar()
  File "/usr/lib64/python3.5/site-packages/yaml/emitter.py", line 268, in expect_scalar
    self.process_scalar()
  File "/usr/lib64/python3.5/site-packages/yaml/emitter.py", line 533, in process_scalar
    self.write_plain(self.analysis.scalar, split)
  File "/usr/lib64/python3.5/site-packages/yaml/emitter.py", line 1131, in write_plain
    self.stream.write(data)
TypeError: a bytes-like object is required, not 'str'

fatal: [think]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}